[package]
name = "bevy_tetris"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true

[dependencies]
bevy = {version = "0.16.1", features = ["serialize"]}
rand = "0.8.5"
serde = "1.0.219"
serde_cbor = "0.11.2"
